// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-hire/ent/predicate"
	"go-hire/ent/user"
	"go-hire/ent/webhook"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WebhookUpdate is the builder for updating Webhook entities.
type WebhookUpdate struct {
	config
	hooks    []Hook
	mutation *WebhookMutation
}

// Where appends a list predicates to the WebhookUpdate builder.
func (wu *WebhookUpdate) Where(ps ...predicate.Webhook) *WebhookUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WebhookUpdate) SetName(s string) *WebhookUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableName(s *string) *WebhookUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetURL sets the "url" field.
func (wu *WebhookUpdate) SetURL(s string) *WebhookUpdate {
	wu.mutation.SetURL(s)
	return wu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableURL(s *string) *WebhookUpdate {
	if s != nil {
		wu.SetURL(*s)
	}
	return wu
}

// SetRequiredVerification sets the "required_verification" field.
func (wu *WebhookUpdate) SetRequiredVerification(b bool) *WebhookUpdate {
	wu.mutation.SetRequiredVerification(b)
	return wu
}

// SetNillableRequiredVerification sets the "required_verification" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableRequiredVerification(b *bool) *WebhookUpdate {
	if b != nil {
		wu.SetRequiredVerification(*b)
	}
	return wu
}

// SetSecretKey sets the "secret_key" field.
func (wu *WebhookUpdate) SetSecretKey(s string) *WebhookUpdate {
	wu.mutation.SetSecretKey(s)
	return wu
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableSecretKey(s *string) *WebhookUpdate {
	if s != nil {
		wu.SetSecretKey(*s)
	}
	return wu
}

// ClearSecretKey clears the value of the "secret_key" field.
func (wu *WebhookUpdate) ClearSecretKey() *WebhookUpdate {
	wu.mutation.ClearSecretKey()
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WebhookUpdate) SetCreatedAt(t time.Time) *WebhookUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableCreatedAt(t *time.Time) *WebhookUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WebhookUpdate) SetUpdatedAt(t time.Time) *WebhookUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WebhookUpdate) SetUserID(u uuid.UUID) *WebhookUpdate {
	wu.mutation.SetUserID(u)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WebhookUpdate) SetNillableUserID(u *uuid.UUID) *WebhookUpdate {
	if u != nil {
		wu.SetUserID(*u)
	}
	return wu
}

// ClearUserID clears the value of the "user_id" field.
func (wu *WebhookUpdate) ClearUserID() *WebhookUpdate {
	wu.mutation.ClearUserID()
	return wu
}

// SetUser sets the "user" edge to the User entity.
func (wu *WebhookUpdate) SetUser(u *User) *WebhookUpdate {
	return wu.SetUserID(u.ID)
}

// Mutation returns the WebhookMutation object of the builder.
func (wu *WebhookUpdate) Mutation() *WebhookMutation {
	return wu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wu *WebhookUpdate) ClearUser() *WebhookUpdate {
	wu.mutation.ClearUser()
	return wu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WebhookUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WebhookUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WebhookUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WebhookUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WebhookUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		v := webhook.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WebhookUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if v, ok := wu.mutation.URL(); ok {
		if err := webhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Webhook.url": %w`, err)}
		}
	}
	return nil
}

func (wu *WebhookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhook.Table, webhook.Columns, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.URL(); ok {
		_spec.SetField(webhook.FieldURL, field.TypeString, value)
	}
	if value, ok := wu.mutation.RequiredVerification(); ok {
		_spec.SetField(webhook.FieldRequiredVerification, field.TypeBool, value)
	}
	if value, ok := wu.mutation.SecretKey(); ok {
		_spec.SetField(webhook.FieldSecretKey, field.TypeString, value)
	}
	if wu.mutation.SecretKeyCleared() {
		_spec.ClearField(webhook.FieldSecretKey, field.TypeString)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(webhook.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if wu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhook.UserTable,
			Columns: []string{webhook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhook.UserTable,
			Columns: []string{webhook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WebhookUpdateOne is the builder for updating a single Webhook entity.
type WebhookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebhookMutation
}

// SetName sets the "name" field.
func (wuo *WebhookUpdateOne) SetName(s string) *WebhookUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableName(s *string) *WebhookUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetURL sets the "url" field.
func (wuo *WebhookUpdateOne) SetURL(s string) *WebhookUpdateOne {
	wuo.mutation.SetURL(s)
	return wuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableURL(s *string) *WebhookUpdateOne {
	if s != nil {
		wuo.SetURL(*s)
	}
	return wuo
}

// SetRequiredVerification sets the "required_verification" field.
func (wuo *WebhookUpdateOne) SetRequiredVerification(b bool) *WebhookUpdateOne {
	wuo.mutation.SetRequiredVerification(b)
	return wuo
}

// SetNillableRequiredVerification sets the "required_verification" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableRequiredVerification(b *bool) *WebhookUpdateOne {
	if b != nil {
		wuo.SetRequiredVerification(*b)
	}
	return wuo
}

// SetSecretKey sets the "secret_key" field.
func (wuo *WebhookUpdateOne) SetSecretKey(s string) *WebhookUpdateOne {
	wuo.mutation.SetSecretKey(s)
	return wuo
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableSecretKey(s *string) *WebhookUpdateOne {
	if s != nil {
		wuo.SetSecretKey(*s)
	}
	return wuo
}

// ClearSecretKey clears the value of the "secret_key" field.
func (wuo *WebhookUpdateOne) ClearSecretKey() *WebhookUpdateOne {
	wuo.mutation.ClearSecretKey()
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WebhookUpdateOne) SetCreatedAt(t time.Time) *WebhookUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableCreatedAt(t *time.Time) *WebhookUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WebhookUpdateOne) SetUpdatedAt(t time.Time) *WebhookUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetUserID sets the "user_id" field.
func (wuo *WebhookUpdateOne) SetUserID(u uuid.UUID) *WebhookUpdateOne {
	wuo.mutation.SetUserID(u)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WebhookUpdateOne) SetNillableUserID(u *uuid.UUID) *WebhookUpdateOne {
	if u != nil {
		wuo.SetUserID(*u)
	}
	return wuo
}

// ClearUserID clears the value of the "user_id" field.
func (wuo *WebhookUpdateOne) ClearUserID() *WebhookUpdateOne {
	wuo.mutation.ClearUserID()
	return wuo
}

// SetUser sets the "user" edge to the User entity.
func (wuo *WebhookUpdateOne) SetUser(u *User) *WebhookUpdateOne {
	return wuo.SetUserID(u.ID)
}

// Mutation returns the WebhookMutation object of the builder.
func (wuo *WebhookUpdateOne) Mutation() *WebhookMutation {
	return wuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wuo *WebhookUpdateOne) ClearUser() *WebhookUpdateOne {
	wuo.mutation.ClearUser()
	return wuo
}

// Where appends a list predicates to the WebhookUpdate builder.
func (wuo *WebhookUpdateOne) Where(ps ...predicate.Webhook) *WebhookUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WebhookUpdateOne) Select(field string, fields ...string) *WebhookUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Webhook entity.
func (wuo *WebhookUpdateOne) Save(ctx context.Context) (*Webhook, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WebhookUpdateOne) SaveX(ctx context.Context) *Webhook {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WebhookUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WebhookUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WebhookUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		v := webhook.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WebhookUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.URL(); ok {
		if err := webhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Webhook.url": %w`, err)}
		}
	}
	return nil
}

func (wuo *WebhookUpdateOne) sqlSave(ctx context.Context) (_node *Webhook, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhook.Table, webhook.Columns, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Webhook.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhook.FieldID)
		for _, f := range fields {
			if !webhook.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.URL(); ok {
		_spec.SetField(webhook.FieldURL, field.TypeString, value)
	}
	if value, ok := wuo.mutation.RequiredVerification(); ok {
		_spec.SetField(webhook.FieldRequiredVerification, field.TypeBool, value)
	}
	if value, ok := wuo.mutation.SecretKey(); ok {
		_spec.SetField(webhook.FieldSecretKey, field.TypeString, value)
	}
	if wuo.mutation.SecretKeyCleared() {
		_spec.ClearField(webhook.FieldSecretKey, field.TypeString)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(webhook.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if wuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhook.UserTable,
			Columns: []string{webhook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhook.UserTable,
			Columns: []string{webhook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Webhook{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
